export enum OtpEnum {
    LOGIN = 'LOGIN',
    PASSWORD_RESET = 'PASSWORD_RESET',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
    MFA_VERIFICATION = 'MFA_VERIFICATION',
}