

export enum PaymentEnum {
      PAYPAL = 'PAYPAL',
      PAYSTACK = 'PAYSTACK',
      FLUTTERWARE = 'FLUTTERWARE'
}


export enum PaymentType {
      DUE_DILIGENT = "PAYMENT_FOR_DUE_DILIGENT",
      BROKER_FEE = "PAYMENT_FOR_BROKER_FEE",
      MANAGEMENT_FEE = "PAYMENT_FOR_DUE_DELIGENT",
      INSPECTION = "PAYMENT_FOR_INSPECTION",
}