export const userValue = [
  'u.id as id',
  'u.id as user_id',
  'u.first_name',
  'u.last_name',
  'u.email',
  'u.phone_number',
  'u.profile',
  'u.image',
  'u.status',
  'u.password',
  'u.ip_address',
  'u.force_password_reset',
  'u.mfa_totp_secret',
  'u.require_authenticator_mfa',
  'u.last_logged_in_at',
  'u.force_password_reset',
  'u.user_agent',
  'u.failed_login_attempts',
  'u.is_email_verified',
  'u.is_phone_verified',
  'u.is_mfa_enabled',
  'u.is_default_password',
  'u.created_at',
  'u.updated_at',
  'u.role_id',
]

export const exculedPasswordUserInfo = [
  'u.id',
  'u.id',
  'u.first_name',
  'u.last_name',
  'u.email',
  'u.phone_number',
  'u.profile',
  'u.image',
  'u.force_password_reset',
  'u.user_agent',
  'u.failed_login_attempts',
  'u.is_email_verified',
  'u.is_phone_verified',
  'u.is_mfa_enabled',
  'u.is_default_password',
  'u.created_at',
  'u.updated_at',
  'u.role_id',
]
