import { z } from "zod";

export const preQualifySchema = z.object({
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().min(1, "Last name is required"),
  email: z.string().email("Invalid email address"),
  phone_number: z.string().min(10, "Phone number must be at least 10 digits"),
  gender: z.enum(["Male", "Female", "Other"]),
  marital_status: z.string().min(1, "Marital status is required"),
  house_number: z.string().optional(),
  street_address: z.string().min(1, "Street address is required"),
  state: z.string().min(1, "State is required"),
  city: z.string().min(1, "City is required"),
  employment_confirmation: z.enum(["Yes", "No"]),
  employment_position: z.string().min(1, "Employment position is required"),
  employer_address: z.string().min(1, "Employer address is required"),
  employer_state: z.string().min(1, "Employer state is required"),
  years_to_retirement: z.number().min(0, "Years to retirement must be non-negative"),
  net_income: z.number().min(0, "Net income must be non-negative"),
  industry_type: z.string().min(1, "Industry type is required"),
  employment_type: z.string().min(1, "Employment type is required"),
  existing_loan_obligation: z.enum(["Yes", "No"]),
  rsa: z.string().min(1, "RSA is required"),
  preferred_developer: z.string().optional(),
  property_name: z.string().min(1, "Property name is required"),
  preferred_lender: z.string().optional(),
  property_id: z.string(),
});
